# Cmd IDs and Response IDs. Autogenerated from header file 
# in CmdResponseDefinitions.h 

STOP_TEST_DRIVE = 0xA502
DO_TEST_DRIVE   = 0xA501
WP_GET_ACTIVE   = 0xA507
CMD_ACCEPT      = 0xA505
CMD_REJECT      = 0xA506


